Fixing #75
Czechitas-Python/python-data-1 pull request #76
Opened 2023-10-11 13:10 UTC by pavelsuk

Fixing #75 

- smazani casti s nakupy
- pridani linku na staty.json z kapitoly [Ruzne](https://kodim.cz/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/ruzne)

Prosim o review. Nejsem si jisty, jestli bude na kodim fungovat ten relativni link do sousedniho adresare, nebo jestli je lepsi to tam dat jako plnou cestu, pripadne zkopirovat staty.json do asset/agregace-a-spojovani.  

@pesikj @ZelenyMartin

2023-10-11 13:12 UTC, pesikj approved these changes

2023-10-11 13:40 UTC, ZelenyMartin requested changes

2023-10-11 13:40 UTC, ZelenyMartin commented on python-pro-data-1/agregace-a-spojovani/ruzne.md
> +Pokud nemáme načtený soubor s daty, načteme si ho. Data si můžeme [stáhnout zde](../podmineny-vyber/assets/staty.json). Opět platí, že si je dáme do adresáře, kde máme právě otevřený terminál!
Toto linkovani do jine lekce asi fungovat nebude. Alespon nam neslo linkovat z cviceni do lekce (taky pres `../`)

2023-10-11 13:43 UTC, ZelenyMartin commented
Ja bych tu cast Pocitane sloupce presunul uplne do te predchozi lekce Podmíněný výběr (napr. jako cteni na doma).

2023-10-11 14:16 UTC, pavelsuk commented on python-pro-data-1/agregace-a-spojovani/ruzne.md
> +Pokud nemáme načtený soubor s daty, načteme si ho. Data si můžeme [stáhnout zde](../podmineny-vyber/assets/staty.json). Opět platí, že si je dáme do adresáře, kde máme právě otevřený terminál!
Jo, neco takoveho si vybavuju. Dik za review.

2023-10-11 14:16 UTC, pavelsuk commented
> Ja bych tu cast Pocitane sloupce presunul uplne do te predchozi lekce Podmíněný výběr (napr. jako cteni na doma).

Zkusim to udelat jeste do tohoto PR

2023-10-11 14:34 UTC, pavelsuk commented
Predelal jsem to [snad] podle [commentu od Martina](https://github.com/Czechitas-Python/python-data-1/pull/76#issuecomment-1757728891) a prijde mi, ze to dava vetsi smysl, nez ten muj puvodni navrh. Navic se tim neborti cele flow nad jednemi daty, ale naopak podporuje.   

Myslel si to tak @ZelenyMartin ?

2023-10-11 14:38 UTC, ZelenyMartin commented
Ja bych, prosim te, celou stranku `python-pro-data-1/agregace-a-spojovani/ruzne.md` presunul do nove podstranky v lekci `python-pro-data-1/podmineny-vyber/` (asi jako cteni na doma) a pridal to do https://github.com/Czechitas-Python/python-data-1/blob/main/python-pro-data-1/podmineny-vyber/entry.yml

Ale jestli se ti do toho nechce, tak to udelam nekdy, jak budu mit cas.

2023-10-11 14:43 UTC, pavelsuk commented
> Ja bych, prosim te, celou stranku `python-pro-data-1/agregace-a-spojovani/ruzne.md` presunul do nove podstranky v lekci `python-pro-data-1/podmineny-vyber/` (asi jako cteni na doma) a pridal to do https://github.com/Czechitas-Python/python-data-1/blob/main/python-pro-data-1/podmineny-vyber/entry.yml
> 
> Ale jestli se ti do toho nechce, tak to udelam nekdy, jak budu mit cas.

Nevim, jestli uplne dobre chapu jak by mel vypadat vysledek a jak otestovat, ze to funguje. S temi yml jsem jeste nedelal. Tak to radeji necham na tobe, aby vysvetlovani netrvalo dele, nez vlastni uprava, jo?

2023-10-11 15:02 UTC, ZelenyMartin commented
> > Ja bych, prosim te, celou stranku `python-pro-data-1/agregace-a-spojovani/ruzne.md` presunul do nove podstranky v lekci `python-pro-data-1/podmineny-vyber/` (asi jako cteni na doma) a pridal to do https://github.com/Czechitas-Python/python-data-1/blob/main/python-pro-data-1/podmineny-vyber/entry.yml
> > Ale jestli se ti do toho nechce, tak to udelam nekdy, jak budu mit cas.
> 
> Nevim, jestli uplne dobre chapu jak by mel vypadat vysledek a jak otestovat, ze to funguje. S temi yml jsem jeste nedelal. Tak to radeji necham na tobe, aby vysvetlovani netrvalo dele, nez vlastni uprava, jo?

Jo, bez obav. Pak udelam svoje nove PR.

2023-11-10 08:11 UTC, ZelenyMartin commented
@pavelsuk ahoj, @pesikj psal, že chce celý pandas kurz předělat do práce s jiným datasetem, tak už bych neřešil dílčí změny do tohoto textu. Navrhuji zavřít issue.

2023-11-10 08:31 UTC, closed without merging