Úpravy textů
Czechitas-Python/python-data-1 pull request #82
Opened 2024-01-07 20:23 UTC by pesikj

2024-01-07 21:11 UTC, ZelenyMartin commented on python-pro-data-1/podmineny-vyber/podmineny-vyber.md
>  import pandas
```suggestion
import pandas as pd
```

2024-01-07 21:12 UTC, ZelenyMartin commented on python-pro-data-1/podmineny-vyber/podmineny-vyber.md
> +food_nutrient = pandas.read_json("food_nutrient.json")
```suggestion
food_nutrient = pd.read_csv("food_nutrient.csv")
```

2024-01-08 12:59 UTC, pesikj commented
Vím o chybějícím souboru, musím upravit skript na jeho generování.

2024-01-09 13:54 UTC, ZelenyMartin commented on python-pro-data-1/agregace-a-spojovani/pokrocile-upravy.md
> +Co v takovém případě udělat? Nejlepší je vždy ověření, proč údaje chybí (např. u poskytovatele dat, v metodice sběru, v programu na export dat) a pokud je to možné, zajistit jejich doplnění. Př ihled
```suggestion
Co v takovém případě udělat? Nejlepší je vždy ověření, proč údaje chybí (např. u poskytovatele dat, v metodice sběru, v programu na export dat) a pokud je to možné, zajistit jejich doplnění. Při hledání příčiny může pomoci i uložení těchto dat do samostatné tabulky, protože v ní můžeme vidět nějaké společné znaky, které tyto neúplné řádky mají. Zkusme si to na našich datech.
```

2024-01-11 09:21 UTC, ZelenyMartin approved these changes
Už bych to nahodil i bez `food_other.csv`.

2024-01-12 16:42 UTC, pesikj commented
@ZelenyMartin Přidal jsem další upravený text a chybějící soubor, podívej se na to, prosím. Pokud to bude OK, můžeme provést merge.

2024-01-12 16:57 UTC, ZelenyMartin requested changes

2024-01-12 16:57 UTC, ZelenyMartin commented on python-pro-data-1/agregace-a-spojovani/propojeni-dat.md
> +Dále si poležme otázku, co se stane, pokud bude nějaká potravina zastoupena pouze v jedné tabulce. Je například možné, že nějakou potravinu máme v tabulce `food`, ale nemáme k ní žádné údaje o výživn
```suggestion
Dále si položme otázku, co se stane, pokud bude nějaká potravina zastoupena pouze v jedné tabulce. Je například možné, že nějakou potravinu máme v tabulce `food`, ale nemáme k ní žádné údaje o výživných látkách. Co v takovém případě máme dělat? A co v případě "anonymních" potravin, o kterých víme výživné látky, ale nemáme je uvedené v tabulce `food`?
```

2024-01-12 18:10 UTC, ZelenyMartin approved these changes

2024-01-12 18:35 UTC, merged